### ISSUE TITLE
Rework how we model "Joint Sessions"

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#6146]
Joint sessions (group A meeting during group B's scheduled session) are currently handled with ad-hoc notes that tie sessions together, so group A has no scheduled Session and nothing appears under /group/A/meetings or /meeting/N/session/A. Rework the data model so joint sessions are represented directly and appear on both groups' meeting/session pages. /secr/sreq already lets chairs request joint sessions but the DB doesn't model them. This is a major remodel; the concept has existed for over a decade. Also backfill historical joint-session history from the recording DocAlias pairs (see #6146).

### Tasks
- [ ] Add a data model that represents a session as jointly held by two or more groups
- [ ] Surface joint sessions on both groups' `/group/<acronym>/meetings` and `/meeting/<n>/session/<acronym>` pages
- [ ] Update /secr/sreq to record joint-session requests against the new model
- [ ] Backfill historical joint-session records from the recording DocAlias pairs

---
**Agent-assisted triage**

- Suggested size: XL
- Suggested priority: major
- Suggested lane: big-bet
- Analysis confidence: high
- Updated with agent assistance on 2026-08-19
---

<details><summary>Original report</summary>

Right now, we use a series of workarounds to deal with joint sessions (group A meets during group B's scheduled session).

The /secr/sreq tool allows chairs to ask for joint sessions, but the database does not model them at all. Rather, we end up with notes in various places that tie the sessions together. Since Group A didn't have a scheduled Session above, nothing appears for the meeting under the /group/`A acronym`/meetings page or under /meeting/`whatevernumber`/session/`A acronym`.

This needs a major remodel - the concept of joint sessions has been around for at _least_ a decade and is not going to go away.

cc: @flynnliz
</details>

**Comment by rjsparks** [comment]
To help with filling in some older backhistory later, here are some DocAlias objects that will go away as part of the feat/rfc work. Note that this is _not_ a complete list of sessions that met jointly with other sessions.

```
recording-91-l2vpn-1-->recording-91-pals-2
recording-91-ntp-2-->recording-91-tictoc-1
recording-91-pce-2-->recording-91-mpls-2
recording-91-pim-1-->recording-91-mboned-1
recording-91-precis-1-->recording-91-dmarc-1
recording-91-pwe3-1-->recording-91-bess-1
recording-91-siprec-1-->recording-91-dispatch-2
recording-94-bfcpbis-1-->recording-94-grow-1
recording-94-bfd-2-->recording-94-spring-1
recording-94-ecrit-2-->recording-94-clue-1
recording-94-opsec-1-->recording-94-l3sm-1
recording-94-radext-2-->recording-94-dime-1
recording-94-t2trg-1-->recording-94-tram-1
recording-94-tictoc-2-->recording-94-ntp-1
recording-95-dprive-2-->recording-95-openpgp-1
recording-95-pim-2-->recording-95-mboned-2
recording-95-tictoc-3-->recording-95-ntp-1
recording-96-aqm-2-->recording-96-tsvwg-2
recording-96-artarea-2-->recording-96-dispatch-1
recording-96-avtcore-3-->recording-96-avtext-2
recording-96-imtg-3-->recording-96-slim-2
recording-96-mile-2-->recording-96-cose-2
recording-96-ntp-3-->recording-96-tram-1
recording-96-ntp-4-->recording-96-rtcweb-2
recording-96-pim-2-->recording-96-mboned-1
recording-96-tictoc-3-->recording-96-tram-1
recording-96-tictoc-4-->recording-96-rtcweb-2
recording-97-avtext-2-->recording-97-avtcore-1
recording-97-modern-2-->recording-97-trans-1
recording-97-pim-2-->recording-97-mboned-1
recording-97-sipbrandy-2-->recording-97-dispatch-1
recording-97-tictoc-2-->recording-97-ntp-1
recording-98-avtcore-1-->recording-98-payload-1
recording-98-mboned-1-->recording-98-pim-1
recording-98-tictoc-1-->recording-98-ntp-1
recording-99-curdle-1-->recording-99-dispatch-1
recording-99-dcrup-1-->recording-99-dmarc-1
recording-99-mpls-3-->recording-99-rtgwg-3
recording-99-pim-1-->recording-99-mboned-1
recording-99-tictoc-1-->recording-99-ntp-1
recording-100-dcrup-1-->recording-100-netvc-1
recording-100-httpbis-1-->recording-100-dispatch-1
recording-100-isis-1-->recording-100-ospf-1
recording-100-lamps-1-->recording-100-ipsecme-1
recording-100-modern-1-->recording-100-extra-1
recording-100-pim-1-->recording-100-mboned-1
recording-100-tictoc-1-->recording-100-ntp-1
recording-101-extra-1-->recording-101-calext-1
recording-101-modern-1-->recording-101-dispatch-1
recording-101-payload-1-->recording-101-avtcore-1
recording-101-pim-1-->recording-101-mboned-1
recording-101-stir-1-->recording-101-sipcore-1
recording-101-tictoc-1-->recording-101-ntp-1
recording-101-xrblock-1-->recording-101-avtcore-1
recording-102-cfrg-2-->recording-102-gaia-2
recording-102-extra-1-->recording-102-mile-2
recording-102-ntp-2-->recording-102-tictoc-2
recording-102-oauth-4-->recording-102-acme-2
recording-102-regext-4-->recording-102-rtcweb-2
recording-102-trans-2-->recording-102-oauth-3
recording-104-acme-2-->recording-104-cfrg-2
recording-104-extra-3-->recording-104-uta-2
recording-104-extra-4-->recording-104-jmap-2
recording-104-netmod-3-->recording-104-netconf-2
recording-104-tictoc-2-->recording-104-ntp-2
recording-105-capport-2-->recording-105-stir-2
recording-106-extra-2-->recording-106-calext-2
recording-106-homenet-2-->recording-106-dnssd-3
```
