### ISSUE TITLE
Make the necessary changes to realize the WIT area

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#6911]
```[tasklist]
### Tasks
- [ ] https://github.com/ietf-tools/datatracker/issues/6912
- [x] Obtain leadership/secretariat review, particularly of the scheduling tool
- [ ] Deploy the datatracker changes to production
- [ ] Create witarea mailing list
- [ ] Close the tsvarea group and list
```

**Comment by rjsparks** [comment]
This moved to manual action by the secretariat
