### ISSUE TITLE
Deploy a development instance demonstrating the new WIT area

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#6912]
```[tasklist]
### Tasks
- [x] create feat/wit branch
- [x] Build migrations that create the new area
- [x] Implement the reassignments at https://mailarchive.ietf.org/arch/msg/ietf/qK_TwOiniQWxonzhkE5AQeK45mg/ in the migrations
- [x] build the new witarea area group
- [x] Deploy branch to dev.ietf.org
- [x] add grouphistory and groupevents
- [x] change the color of WIT in the schedule editor to match tsv
- [ ] leave tsvarea in tsv and close it
- [ ] make Francesca and Zahed chairs of witarea (coinflip for who is responsible AD)
```

**Comment by rjsparks** [comment]
We should leave GroupEvent objects noting the moves.

**Comment by rjsparks** [comment]
The rest of this moved to manual action by the secretariat
