### ISSUE TITLE
ffgfffgfgffgfg

### ISSUE THREAD

**Issue by terminatorWG** [ietf-tools/datatracker#7158]
### Description

CODE_OF_CONDUCT.md

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
```[tasklist]
### Tasks
- [ ] https://github.com/ietf-tools/datatracker/issues/7155
- [ ] https://github.com/ietf-tools/datatracker/pull/7154
- [ ] https://github.com/ietf-tools/datatracker/pull/7134
```
