### ISSUE TITLE
Psiphon pro

### ISSUE THREAD

**Issue by SAEED17fard** [ietf-tools/datatracker#7568]
### Describe the issue

Herders name and value http and ssh 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
```[tasklist]
### Tasks
- [ ] https://github.com/ietf-tools/datatracker/pull/7567
- [ ] https://github.com/ietf-tools/datatracker/pull/7564
- [ ] https://github.com/ietf-tools/datatracker/issues/7563
- [x] Ssh-http
```

```[tasklist]
### Tasks
- [ ] https://github.com/ietf-tools/datatracker/issues/7565
- [ ] https://github.com/ietf-tools/datatracker/pull/7567
- [ ] https://github.com/ietf-tools/datatracker/pull/7516
- [ ] https://github.com/ietf-tools/datatracker/pull/7547
```

**Comment by SAEED17fard** [comment]
Config Psiphon
