### ISSUE TITLE
Make bluesheets upload more flexible

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#7804]
Bluesheets upload is too strict about MIME-type detection (a simple .txt file was rejected as application/csv), wasting time. Loosen MIME detection and, ideally, allow pasting bluesheet content directly as is already possible for agendas. See #7804.

### Tasks
- [ ] Relax MIME-type detection for bluesheets upload
- [ ] Allow pasting bluesheet content directly

---
**Agent-assisted triage**

- Suggested size: M
- Suggested priority: minor
- Suggested lane: standard
- Analysis confidence: medium
- Updated with agent assistance on 2026-08-18
---

<details><summary>Original report</summary>

### Description

From: 	"Martin Duke" <martin.h.duke@gmail.com>
To: 	support@ietf.org
Subject: 	Bluesheets Upload
Date: 	Wed, 7 Aug 2024 10:29:50 -0700

Can datatracker be less strict about MIME types for bluesheets upload? I have a very simple .txt file that seems to be assigned the application/csv MIME type. I guess this is because the format of the bluesheet is
< name >, < affiliation >

it is not obvious how to fix this, and it is wasting a huge amount of time.

Even better, just allow us to cut and paste the bluesheets in directly, as we can do for the agenda.

Thanks
Martin

cc @martinduke

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
</details>

**Comment by Duncun76918** [comment]
@duncun0918
